version: '3.7'

services:
  db:
    image: postgres:15.4-alpine3.18 
    env_file:
      - .env.db.dev
    ports:
      - "5432:5432"
  api:
    build: 
      context: ../api
      dockerfile: Dockerfile
    container_name: rdis_api
    volumes:
      - ../api:/app
      - node_modules_api:/app/node_modules
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - db
    env_file:
      - .env.dev
    command: npm run dev
  web:
    build: ../web
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ../web:/app
      - node_modules_web:/app/node_modules
    command: npm start

volumes:
  node_modules_api:
  node_modules_web: