name: API CI
on: push

jobs:
  test_build_push:
    runs-on: ubuntu-22.04
    services:
      cache:
        image: redis:6.0.20-alpine3.18
      db:
        image: postgres:15.4-alpine3.18
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: rdisuserdev
          POSTGRES_PASSWORD: rdispassdev
          POSTGRES_DB: rdisdb
    steps:
      - uses: actions/checkout@v3
      - name: Testing API CI
        run: |
          cd api
          bash test.sh