name: Web CI
on: push

jobs:
  test_build_push:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Testing Web CI
        run: |
          cd web
          bash test.sh